#!/bin/sh
set -e

lb config noauto \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architecture amd64 \
    --linux-flavours amd64 \
    --binary-images iso-hybrid \
    --debian-installer live \
    --debian-installer-gui true \
    --mirror-bootstrap "http://deb.debian.org/debian" \
    --mirror-chroot "http://deb.debian.org/debian" \
    --mirror-chroot-security "http://security.debian.org/debian-security" \
    --mirror-binary "http://deb.debian.org/debian" \
    --mirror-binary-security "http://security.debian.org/debian-security" \
    --keyring-packages "debian-archive-keyring" \
    --iso-application "Uhuru OS - Awamu 2 (Majaribio ya Ndani)" \
    --iso-publisher "Letema Group Tech" \
    --iso-volume "UHURU-OS-A2" \
    --memtest none \
    --win32-loader false \
    --apt-recommends true \
    --firmware-chroot true \
    --firmware-binary true \
    --bootappend-live "boot=live components username=mtumiaji hostname=uhuru-os locales=sw_TZ.UTF-8 keyboard-layouts=us" \
    "${@}"
